# Pre-Assembling

### --- Libraries importieren ---

In [1]:
import pandas as pd
import numpy as np
import anndata as ad
import re
import csv

from scipy.sparse import coo_matrix
from scipy.io import mmwrite
from pathlib import Path

import sctoolbox
import sctoolbox.utils as utils
import sctoolbox.utils.assemblers as assembler

### --- Datei einlesen ---

In [2]:
file_path_meta = "/home/stud9/notebooks/rna_analysis/notebooks/ScRNA-analysis/testdaten_meta_studis_values.txt"
meta_df = pd.read_csv(file_path_meta, decimal=",", sep="\t")
meta_df = meta_df.fillna(0)
meta_df.head()

,export_psn,mnpvisid,mnpcvpid,mnpvislabel,gec_cv_hypert,gec_cv_chd,gec_cv_mi,anam_herz3,ang_pect,ang_pect1,lvedv,lvesv,schlagvolumen,pulm_syst_geschw,pulm_dias_geschw,gec_pd_copd,gec_pd_hypert,gec_vitals_so2
0,pop_0001,365,1036502,Visite 1-VO,0,0,0,0.0,1.0,1.0,70.0,26.0,44.0,72.0,44.0,0,0,96.0
1,pop_0001,1850,1185004,Visite 2-VO,1,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,98.0
2,pop_0002,365,2036502,Visite 1-VO,1,0,0,0.0,0.0,0.0,0.0,0.0,68.0,0.0,0.0,0,0,93.0
3,pop_0002,1850,2185004,Visite 2-VO,1,0,0,0.0,0.0,0.0,137.0,57.0,85.0,47.0,35.0,0,0,96.0
4,pop_0002,3011,2301106,Visite 3-VO,1,0,0,0.0,0.0,0.0,54.0,17.0,41.0,33.0,37.0,0,0,95.0

In [3]:
meta_df["mnpvislabel"].value_counts()

mnpvislabel
Visite 1-VO    688
Visite 2-VO    305
Visite 3-VO    255
Visite 4-VO     64
Name: count, dtype: int64

In [4]:
meta_df = meta_df.loc[meta_df["mnpvislabel"] == "Visite 1-VO"]
meta_df.head()

,export_psn,mnpvisid,mnpcvpid,mnpvislabel,gec_cv_hypert,gec_cv_chd,gec_cv_mi,anam_herz3,ang_pect,ang_pect1,lvedv,lvesv,schlagvolumen,pulm_syst_geschw,pulm_dias_geschw,gec_pd_copd,gec_pd_hypert,gec_vitals_so2
0,pop_0001,365,1036502,Visite 1-VO,0,0,0,0.0,1.0,1.0,70.0,26.0,44.0,72.0,44.0,0,0,96.0
2,pop_0002,365,2036502,Visite 1-VO,1,0,0,0.0,0.0,0.0,0.0,0.0,68.0,0.0,0.0,0,0,93.0
5,pop_0003,365,3036502,Visite 1-VO,0,0,0,0.0,0.0,0.0,0.0,0.0,60.0,0.0,0.0,0,0,97.0
6,pop_0004,365,4036502,Visite 1-VO,0,0,0,0.0,1.0,0.0,94.0,34.0,60.0,56.0,43.0,0,0,100.0
9,pop_0005,365,5036502,Visite 1-VO,0,0,0,0.0,0.0,0.0,0.0,0.0,56.0,0.0,0.0,0,0,95.0

In [5]:
file_path_pat = "/mnt/workspace_stud/napkon_data/wp2_rna/out.txt"
file_path_gene = "/mnt/workspace_stud/napkon_data/wp2_rna/combined_rna_napkon_4_all.matrix.raw.anno"


path_mtx = str(Path.cwd()) # Aktueller Speicherort/Verzeichnis mit .mtx, barcodes.tsv und genes.tsv
print(path_mtx)

/home/stud9/notebooks/rna_analysis/notebooks/ScRNA-analysis

### 1. --- Patienten-Metadaten lesen und vorbereiten für Assemblierung ---

In [6]:
pat_df = pd.read_csv(file_path_pat, decimal=",", sep="\t")
pat_df = pat_df.rename(columns={"meta pop export_psn":"export_psn"})

# 'Neue' Metadaten zu 'alten' Metadaten hinzufügen
pat_df = pd.merge(pat_df, meta_df, how='left', on=["export_psn"])
pat_df = pat_df.fillna(0)
pat_df.head()

,TubeID,meta TubeID,export_psn,meta pop visit_1_date,meta pop visit_2_date,meta pop visit_3_date,meta pop visit_4_date,meta pop age,meta pop age_dec,meta pop sex,...,ang_pect,ang_pect1,lvedv,lvesv,schlagvolumen,pulm_syst_geschw,pulm_dias_geschw,gec_pd_copd,gec_pd_hypert,gec_vitals_so2
0,NA0037972575,NA0037972575,0,0,0,0,0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,LV3001132258,LV3001132258,0,0,0,0,0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,G204801567,G204801567,0,0,0,0,0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,G204801566,G204801566,0,0,0,0,0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,LV1007699809,LV1007699809,0,0,0,0,0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
pat_df["rna project.run id"] # ID überprüfen

0                         0
1          plt5.run1 pat_26
2                         0
3                         0
4         plt2.run1 pat_195
               ...
3771    plt33.run1 pat_2384
3772    plt38.run1 pat_2741
3773    plt40.run1 pat_3006
3774    plt40.run1 pat_3033
3775      plt1.run1 pat_146
Name: rna project.run id, Length: 3776, dtype: object

In [8]:
# optional: Patienten-Datei im lokalen Speicherort abspeichern
# pat_df.to_csv('pat_meta.csv', index=False)

### 2. --- Gen-Metadaten lesen und vorbereiten für Assemblierung ---

In [9]:
data = []

with open(file_path_gene, 'r') as file:
    content = file.read()
    lines = content.splitlines()

    header = lines[0].split('\t')

    for line in lines[1:]:
        elements = line.split('\t')
        data.append(elements)

gene_df = pd.DataFrame(data, columns=header)
gene_df.head()

,Ensembl gene id,Ensembl gene,Ensembl biotype,UniProt proteins,UniProt genes,UniProt accessions,UniProt names,UniProt Ensembl transcripts,UniProt Ensembl proteins,UniProt Ensembl gene ids,...,plt49.run1 pat_3563,plt49.run1 pat_3564,plt49.run1 pat_3565,plt49.run1 pat_3566,plt49.run1 pat_3567,plt49.run1 pat_3568,plt49.run1 pat_3569,plt49.run1 pat_3570,plt49.run1 pat_3571,plt49.run1 pat_3572
0,ENSG00000146555,SDK1,protein_coding,Protein sidekick-1,SDK1,Q7Z5N4; F8W6X9; A0A087WTQ6,SDK1_HUMAN; F8W6X9_HUMAN; A0A087WTQ6_HUMAN,ENST00000404826; ENST00000389531; ENST00000615806,ENSP00000385899; ENSP00000374182; ENSP00000478062,ENSG00000146555,...,5,2,2,0,2,0,1,2,1,0
1,ENSG00000283537,ENSG00000283537,transcribed_unprocessed_pseudogene,,,,,,,ENSG00000283537,...,0,0,1,0,0,0,0,0,0,0
2,ENSG00000166523,CLEC4E,protein_coding,C-type lectin domain family 4 member E,"CLEC4E, CLECSF9, MINCLE, UNQ218/PRO244; CLEC4E",Q9ULY5; F8WFA1; F5H5X7,CLC4E_HUMAN; F8WFA1_HUMAN; F5H5X7_HUMAN,"ENST00000299663; ENST00000446457, ENST00000450...","ENSP00000299663; ENSP00000387737, ENSP00000404...",ENSG00000166523,...,198,96,90,287,309,94,62,215,261,131
3,ENSG00000125945,ZNF436,protein_coding,Zinc finger protein 436,"ZNF436, KIAA1710",Q9C0F3,ZN436_HUMAN,"ENST00000314011, ENST00000374608, ENST00000635...","ENSP00000313582, ENSP00000363736, ENSP00000489...",ENSG00000125945,...,40,21,70,39,71,15,26,66,41,17
4,ENSG00000206145,P2RX6P,transcribed_unprocessed_pseudogene,,,,,,,ENSG00000206145,...,0,0,0,0,0,1,0,1,0,0

In [10]:
gene_df = gene_df.replace(to_replace='', value=0)
gene_df.head()

,Ensembl gene id,Ensembl gene,Ensembl biotype,UniProt proteins,UniProt genes,UniProt accessions,UniProt names,UniProt Ensembl transcripts,UniProt Ensembl proteins,UniProt Ensembl gene ids,...,plt49.run1 pat_3563,plt49.run1 pat_3564,plt49.run1 pat_3565,plt49.run1 pat_3566,plt49.run1 pat_3567,plt49.run1 pat_3568,plt49.run1 pat_3569,plt49.run1 pat_3570,plt49.run1 pat_3571,plt49.run1 pat_3572
0,ENSG00000146555,SDK1,protein_coding,Protein sidekick-1,SDK1,Q7Z5N4; F8W6X9; A0A087WTQ6,SDK1_HUMAN; F8W6X9_HUMAN; A0A087WTQ6_HUMAN,ENST00000404826; ENST00000389531; ENST00000615806,ENSP00000385899; ENSP00000374182; ENSP00000478062,ENSG00000146555,...,5,2,2,0,2,0,1,2,1,0
1,ENSG00000283537,ENSG00000283537,transcribed_unprocessed_pseudogene,0,0,0,0,0,0,ENSG00000283537,...,0,0,1,0,0,0,0,0,0,0
2,ENSG00000166523,CLEC4E,protein_coding,C-type lectin domain family 4 member E,"CLEC4E, CLECSF9, MINCLE, UNQ218/PRO244; CLEC4E",Q9ULY5; F8WFA1; F5H5X7,CLC4E_HUMAN; F8WFA1_HUMAN; F5H5X7_HUMAN,"ENST00000299663; ENST00000446457, ENST00000450...","ENSP00000299663; ENSP00000387737, ENSP00000404...",ENSG00000166523,...,198,96,90,287,309,94,62,215,261,131
3,ENSG00000125945,ZNF436,protein_coding,Zinc finger protein 436,"ZNF436, KIAA1710",Q9C0F3,ZN436_HUMAN,"ENST00000314011, ENST00000374608, ENST00000635...","ENSP00000313582, ENSP00000363736, ENSP00000489...",ENSG00000125945,...,40,21,70,39,71,15,26,66,41,17
4,ENSG00000206145,P2RX6P,transcribed_unprocessed_pseudogene,0,0,0,0,0,0,ENSG00000206145,...,0,0,0,0,0,1,0,1,0,0

In [11]:
gene_df.to_csv('gene_meta.csv', index=False) # Gen-Datei speichern

In [12]:
# Falls bereits abgespeichert
# gene_df = pd.read_csv('/mnt/workspace_stud/stud11/ScRNA-analysis/gene_meta.csv')
# gene_df.head()

In [13]:
features = gene_df.loc[:,['Ensembl gene', 'Ensembl gene id', 'Ensembl biotype', 'UniProt proteins', 'UniProt genes', 'UniProt accessions', 'UniProt names', 'UniProt Ensembl transcripts', 'UniProt Ensembl proteins', 'UniProt Ensembl gene ids', 'Ensembl chr', 'Ensembl start', 'Ensembl stop', 'Ensembl strand', 'KEGG PATHWAY terms', 'KEGG PATHWAY ids', 'Gene Ontology terms', 'Gene Ontology ids']] # Auswahl der ersten 18 Spalten -> die Gene ids und Spalten mit Metadaten
features.head()

,Ensembl gene,Ensembl gene id,Ensembl biotype,UniProt proteins,UniProt genes,UniProt accessions,UniProt names,UniProt Ensembl transcripts,UniProt Ensembl proteins,UniProt Ensembl gene ids,Ensembl chr,Ensembl start,Ensembl stop,Ensembl strand,KEGG PATHWAY terms,KEGG PATHWAY ids,Gene Ontology terms,Gene Ontology ids
0,SDK1,ENSG00000146555,protein_coding,Protein sidekick-1,SDK1,Q7Z5N4; F8W6X9; A0A087WTQ6,SDK1_HUMAN; F8W6X9_HUMAN; A0A087WTQ6_HUMAN,ENST00000404826; ENST00000389531; ENST00000615806,ENSP00000385899; ENSP00000374182; ENSP00000478062,ENSG00000146555,chr7,3301252,4269000,+,0,0,"eye development, neural retina development, bi...","GO:0001654, GO:0003407, GO:0005488, GO:0005515..."
1,ENSG00000283537,ENSG00000283537,transcribed_unprocessed_pseudogene,0,0,0,0,0,0,ENSG00000283537,chr7,143620943,143645675,+,0,0,0,0
2,CLEC4E,ENSG00000166523,protein_coding,C-type lectin domain family 4 member E,"CLEC4E, CLECSF9, MINCLE, UNQ218/PRO244; CLEC4E",Q9ULY5; F8WFA1; F5H5X7,CLC4E_HUMAN; F8WFA1_HUMAN; F5H5X7_HUMAN,"ENST00000299663; ENST00000446457, ENST00000450...","ENSP00000299663; ENSP00000387737, ENSP00000404...",ENSG00000166523,chr12,8533305,8540905,-,Tuberculosis,hsa05152,"cell activation, cytokine production, regulati...","GO:0001775, GO:0001816, GO:0001817, GO:0001819..."
3,ZNF436,ENSG00000125945,protein_coding,Zinc finger protein 436,"ZNF436, KIAA1710",Q9C0F3,ZN436_HUMAN,"ENST00000314011, ENST00000374608, ENST00000635...","ENSP00000313582, ENSP00000363736, ENSP00000489...",ENSG00000125945,chr1,23359448,23369836,-,0,0,nucleic acid binding transcription factor acti...,"GO:0001071, GO:0003676, GO:0003677, GO:0003700..."
4,P2RX6P,ENSG00000206145,transcribed_unprocessed_pseudogene,0,0,0,0,0,0,ENSG00000206145,chr22,21035243,21045017,-,0,0,0,0

In [14]:
# Funktion zur Erzeugung eindeutiger Gennamen
def make_unique(names):
    seen = {} 
    unique_names = []
    
    for name in names:
        if name in seen:
            seen[name] += 1
            new_name = f"{name}_{seen[name]}"  # Anhängen von _1, _2, _3, etc.
        else:
            seen[name] = 0
            new_name = name
        
        unique_names.append(new_name)
    
    return unique_names

# Sicherstellen, dass Namen als Strings behandelt werden
features['Ensembl gene'] = features['Ensembl gene'].astype(str)

# Namen eindeutig machen
features['Ensembl gene'] = make_unique(features['Ensembl gene'])

In [15]:
pd.set_option('display.max_rows', None)  # Keine Zeilenbegrenzung

In [16]:
print(features['Ensembl gene'])

0                             SDK1
1                  ENSG00000283537
2                           CLEC4E
3                           ZNF436
4                           P2RX6P
5                             GDI1
6                           TAPBPL
7                            ARNTL
8                  ENSG00000258679
9                          S100A12
10                 ENSG00000273253
11                           MED11
12                            ATL3
13                          ZNF772
14                        C12orf43
15                            IL10
16                       LIX1L-AS1
17                         TRIM49B
18                      CYP2U1-AS1
19                         RSL24D1
20                       LINC02009
21                           ERAL1
22                 ENSG00000234859
23                 ENSG00000286428
24                 ENSG00000268601
25                 ENSG00000232245
26                 ENSG00000271882
27                          ANAPC4
28                 ENSG00000242375
29                            PGA5
30                          PROS2P
31                          SLC7A9
32                 ENSG00000287963
33                 ENSG00000275024
34                 ENSG00000271938
35                 ENSG00000286665
36                        TLR8-AS1
37                          OR2L1P
38                          OR10H5
39                           TAF1A
40                 ENSG00000265737
41                              U4
42                        RPL13AP5
43                          MGAT4B
44                          MLLT10
45                          RAD54L
46                 ENSG00000265781
47                         PA2G4P1
48                          RPS7P2
49                          PNMA6B
50                 ENSG00000278903
51                 ENSG00000231881
52                         ARHGAP6
53                            MXD1
54                           RPAIN
55                 ENSG00000258927
56                        C1orf147
57                 ENSG00000251244
58                           MAPK1
59                           WDR41
60                            PPT2
61                         TMEM245
62                 ENSG00000248288
63                           Y_RNA
64                          NFU1P1
65                            NFE4
66                         SAMMSON
67                            DNM1
68                           GPR84
69                          PTGES3
70                           INHBA
71                          LDHBP1
72                            PIGN
73                       LINC02646
74                          CCDC50
75                           CLIP1
76                 ENSG00000261178
77                 ENSG00000286340
78                       LINC00648
79                           FXYD1
80                        FLJ40194
81                         DNAJC12
82                           CENPU
83                 ENSG00000273138
84                            ENC1
85                 ENSG00000241494
86                 ENSG00000259033
87                 ENSG00000271843
88                        TAB2-AS1
89                 ENSG00000272661
90                         CACNA1G
91                            LMO1
92                         NBPF17P
93                            XKRX
94                 ENSG00000275582
95                           ACTN4
96                 ENSG00000286242
97                        CACYBPP3
98                          MRPL13
99                 ENSG00000267610
100                           TNIK
101                ENSG00000267784
102                ENSG00000267284
103                       CD44-AS1
104                           GJB7
105                        NDUFAF5
106                          SNX16
107                           POLK
108                          MANCR
109                    Metazoa_SRP
110                         CRAMP1
111                         OTUD7B
112                        DYNLRB2
113                         PKNOX1
114                            HLF
115                ENSG00000276814
116                ENSG00000271088
117                ENSG00000277969
118                ENSG00000269924
119                        PPP2R1B
120                          CENPF
121                      RN7SL652P
122                        MUC20P1
123                        METTL2A
124                        FAM242A
125                      RPL36AP48
126                   PRICKLE2-AS3
127                ENSG00000279086
128                ENSG00000288066
129                ENSG00000228399
130                          PKMP4
131                ENSG00000259275
132                ENSG00000259775
133                ENSG00000239991
134                      CDC42-IT1
135                ENSG00000258824
136                         CDC14A
137                         MIR340
138                ENSG00000219699
139                ENSG00000261448
140                        VDAC1P8
141                      LINC02307
142                      POC1B-AS1
143                          FLAD1
144                ENSG00000287730
145                       GAPDHP45
146                ENSG00000287230
147                     SEC24B-AS1
148                         KCNAB2
149                ENSG00000224001
150                           SMPX
151                       B4GALNT1
152                         SEPHS1
153                ENSG00000272077
154                ENSG00000269176
155                      LINC02199
156                         SDR9C7
157                       HNRNPFP1
158                       IMPDH1P2
159                           IL27
160                ENSG00000213036
161                       FABP5P11
162                ENSG00000279130
163                        SNORD11
164                        TMA16P2
165                        SPARCL1
166                         KCNE1B
167                        FAM241A
168                ENSG00000254910
169                ENSG00000282836
170                          LRIG3
171                ENSG00000226239
172                ENSG00000285549
173                ENSG00000267892
174                ENSG00000223612
175                ENSG00000257634
176                        FAM170A
177                ENSG00000229180
178                          KLF11
179                ENSG00000255173
180                ENSG00000254139
181                          FSCN3
182                ENSG00000260017
183                ENSG00000286975
184                          NTRK3
185                          IL1R1
186                ENSG00000281849
187                         KDELR1
188                       RPL21P91
189                         PRKACA
190                         PPP3CA
191                          LOXL2
192                       C11orf80
193                      RPL21P116
194                ENSG00000259408
195                       HMGN1P37
196                          ASB16
197                         RRN3P4
198                         GPCPD1
199                       PCCA-AS1
200                          GPHA2
201                          LRP10
202                        MIR6783
203                        SNORD94
204                ENSG00000267098
205                ENSG00000263326
206                ENSG00000261320
207                ENSG00000279936
208                        SNX18P3
209                          FUT10
210                         CNN2P1
211                         GRIN2A
212                ENSG00000262332
213                     SNAP25-AS1
214                      LINC02029
215                       HSPE1P26
216                ENSG00000269970
217                         RPS27L
218                ENSG00000260911
219                       RNVU1-34
220                          DDX3X
221                       IGHV3-22
222                       SLC16A11
223                           PIGT
224                       IGHV3-47
225                ENSG00000121388
226                ENSG00000288595
227                        CCDC189
228                ENSG00000287187
229                       AOAH-IT1
230                           CDT1
231                     ARHGAP42P3
232                ENSG00000243885
233                ENSG00000286060
234                ENSG00000177452
235                           YBX3
236                ENSG00000261055
237                       TMEM183A
238                ENSG00000287418
239                          SUSD3
240                         MIR324
241                           EOGT
242                ENSG00000229019
243                          TEKT3
244                ENSG00000234902
245                ENSG00000262495
246                         CRYBA4
247                ENSG00000243089
248                          SPA17
249                ENSG00000272971
250                        PTMAP10
251                         PRDM10
252                       PRAMEF19
253                       RNU6-46P
254                       CD200R1L
255                          RPL39
256                           NRAS
257                            TEK
258                ENSG00000261722
259                ENSG00000261222
260                ENSG00000264215
261                ENSG00000284676
262                          SENP7
263                           LRP3
264                         TIMM23
265                ENSG00000251410
266                          CPLX4
267                          CDHR1
268                         CEP170
269                         LRTOMT
270                           ST7L
271                ENSG00000249592
272                         FNDC10
273                         ZPLD2P
274                ENSG00000244738
275                         VPS13D
276                ENSG00000267152
277                          STAP2
278                ENSG00000279742
279                      METTL15P1
280                      MUC5B-AS1
281                           KRT1
282                       TMEM150A
283                        Y_RNA_1
284                      RPL21P127
285                          NR4A2
286                      RN7SL836P
287                          SRRM4
288                           GRM6
289                ENSG00000287677
290                          AIFM3
291                          WDR27
292                        IGBP1P5
293                          DUS1L
294                     ZBTB20-AS3
295                          RSPO1
296                         ADGRL2
297                ENSG00000279340
298                          ZNF69
299                          FOXE3
300                ENSG00000254027
301                         FAM95C
302                        NR4A1AS
303                         WBP1P2
304                    SLC26A4-AS1
305                          ERCC8
306                           MMP2
307                      MRPS18BP1
308                           TAL1
309                             U3
310                           OPN5
311                          FEM1C
312                         ZNF837
313                         MTERF2
314                       PABPC1P4
315                          SEC63
316                        ATG16L1
317                         ACTR1A
318                ENSG00000266184
319                          RAB6C
320                         ARFIP1
321                      MIR2052HG
322                ENSG00000260920
323                          DYRK3
324                        FAM221A
325                         CYP2J2
326                           CHIA
327                         DROSHA
328                       C14orf28
329                        SULT1C3
330                           CHN1
331                         SORBS3
332                           IRX6
333                ENSG00000260126
334                        PCDHGB4
335                           WWC1
336                         SEC61G
337                      SLC25A3P3
338                ENSG00000275185
339                        SLC15A5
340                ENSG00000267606
341                         MGAT4D
342                ENSG00000228174
343                         PKP4P1
344                        TMEM192
345                         TMEM11
346                        UBE2FP2
347                        SNORA62
348                        MIR3173
349                ENSG00000248469
350                         BPIFB4
351                          GPR52
352                         NYNRIN
353                         RNF123
354                        RASGRP1
355                       RPL21P11
356                ENSG00000264125
357                          GTDC1
358                          CAPN9
359                      LINC01405
360                         WWP1P1
361                         GPR135
362                ENSG00000288685
363                ENSG00000279665
364                         ZFAND5
365                      LINC01089
366                         WASF5P
367                        RBBP4P4
368                      RNF32-AS1
369                ENSG00000255801
370                     RNU6-1275P
371                ENSG00000285613
372                ENSG00000279428
373                          SCML1
374                ENSG00000233478
375                ENSG00000272540
376                        PYROXD1
377                ENSG00000285861
378                ENSG00000257113
379                        UPK3BP1
380                          CNPY2
381                ENSG00000216475
382                ENSG00000250725
383                      LINC00578
384                ENSG00000285705
385                           SGCA
386                ENSG00000285205
387                    C5orf66-AS2
388                            FYN
389                          RWDD3
390                ENSG00000279283
391                           AKT2
392                          ATP23
393                           MPP6
394                          TADA3
395                      LINC01933
396                       USP9YP14
397                          MEX3A
398                ENSG00000278727
399                ENSG00000271401
400                          INPP1
401                       IGHV3-38
402                          GRID2
403                          IGLJ2
404                ENSG00000272914
405                          UBE2B
406                          HINT1
407                           NGRN
408                ENSG00000268034
409                ENSG00000258203
410                      RN7SL468P
411                        MIR4748
412                          ENPP4
413                     VSTM2A-OT1
414                        PTPN2P2
415                           DAG1
416                ENSG00000287967
417                           TPM2
418                ENSG00000228206
419                ENSG00000228444
420                      EEF1A1P17
421                           MYF6
422                      THBS1-IT1
423                ENSG00000250866
424                     SLC1A2-AS1
425                     SNORA74C-1
426                        MIR4786
427                      EEF1A1P19
428                          CKAP4
429                          LIMA1
430                       EBNA1BP2
431                ENSG00000254701
432                ENSG00000288080
433                      LINC02097
434                ENSG00000180458
435                        MIR6777
436                         THNSL2
437                ENSG00000237389
438                      CRTC3-AS1
439                       GOLGA8VP
440                          EP300
441                ENSG00000259931
442                ENSG00000248503
443                ENSG00000284966
444                ENSG00000239470
445                          FOXN4
446                ENSG00000275636
447                       RPL10P16
448                ENSG00000256835
449                          RIOK3
450                          RSPO4
451                         ATP1A4
452                           JUND
453                      LINC02065
454                      LINC01191
455                ENSG00000260101
456                         CLEC4D
457                ENSG00000286936
458                          PDZD2
459                         SLC5A6
460                         CLDN10
461                         SYF2P2
462                ENSG00000286787
463                       HS3ST3B1
464                        PCDHGB3
465                         GTF2H3
466                           TSC2
467                ENSG00000286731
468                ENSG00000273257
469                      LINC02812
470                     RPH3AL-AS1
471                         OGFRP1
472                      LINC01767
473                ENSG00000231125
474                       RPL31P11
475                ENSG00000234112
476                        SLC16A7
477                          FREM2
478                      LINC01447
479                           RGS5
480                           FUT4
481                          CHSY3
482                          DLEU2
483                      LINC02446
484                       IMPDH1P7
485                        DEFB118
486                      RNU6-786P
487                      ASAP1-IT2
488                ENSG00000259081
489                ENSG00000259390
490                          MYH16
491                         OPALIN
492                        CNTNAP3
493                ENSG00000287709
494                ENSG00000287209
495                          SPRY1
496                ENSG00000233064
497                          OR4K2
498                ENSG00000257769
499                ENSG00000226664
500                ENSG00000273474
501                ENSG00000272817
502                          RPP14
503                ENSG00000273348
504                         CCDC22
505                ENSG00000255447
506                           QPRT
507                         TREML1
508                       RAD51AP1
509                ENSG00000280070
510                        PCOLCE2
511                ENSG00000229960
512                ENSG00000260877
513                ENSG00000278769
514                         ZSWIM1
515                        PPIAP36
516                ENSG00000145063
517                     HS1BP3-IT1
518                           NPAT
519                      LRRC37A7P
520                ENSG00000256568
521                        TMEM234
522                ENSG00000287061
523                          FCRLB
524                ENSG00000232918
525                ENSG00000234311
526                       SLC25A51
527                       RNVU1-27
528                          FANCE
529                        NPAP1P6
530                     ZNF341-AS1
531                         TRAV24
532                ENSG00000227910
533                ENSG00000226877
534                       IGHV5-51
535                ENSG00000272735
536                          AGMAT
537                         ZNF681
538                           PLK4
539                ENSG00000253194
540                ENSG00000262967
541                         ZNF232
542                         ATP1A1
543                ENSG00000183562
544                      SGMS1-AS1
545                         GABRG3
546                          SRSF1
547                ENSG00000273056
548                      LINC01882
549                ENSG00000286086
550                           MRM3
551                ENSG00000227544
552                          TTC34
553                ENSG00000249483
554                       EEF1E1P1
555                ENSG00000253520
556                           ANKH
557                            ID3
558                      ZNF736P6Y
559                        ALDH9A1
560                ENSG00000260664
561                           HELQ
562                ENSG00000259219
563                      LINC02284
564                ENSG00000219150
565                ENSG00000276768
566                            TEF
567                        MTHFD2L
568                ENSG00000286118
569                ENSG00000262370
570                           TUFM

In [17]:
pd.reset_option('display.max_rows')

In [18]:
features.to_csv("variables.tsv", sep="\t", index=False, header=False) # Variables-Datei speichern

### 3. --- Barcodes Datei aus Patienten-Metadaten erstellen ---

In [19]:
# Barcodes-Datei (Patienten + Metadaten)

patient_ids = gene_df.columns[18:]  # Patienten-Spalten starten ab Spalte 18 
patient_ids

Index(['plt1.run1 pat_88', 'plt1.run1 pat_89', 'plt1.run1 pat_90',
       'plt1.run1 pat_91', 'plt1.run1 pat_92', 'plt1.run1 pat_93',
       'plt1.run1 pat_94', 'plt1.run1 pat_95', 'plt1.run1 pat_96',
       'plt1.run1 pat_97',
       ...
       'plt49.run1 pat_3563', 'plt49.run1 pat_3564', 'plt49.run1 pat_3565',
       'plt49.run1 pat_3566', 'plt49.run1 pat_3567', 'plt49.run1 pat_3568',
       'plt49.run1 pat_3569', 'plt49.run1 pat_3570', 'plt49.run1 pat_3571',
       'plt49.run1 pat_3572'],
      dtype='object', length=3661)

In [20]:
barcodes = pd.DataFrame({
    "rna project.run id": patient_ids # Benennung der Spalte in barcodes.tsv mit "rna project.run id"
}).merge(pat_df, left_on="rna project.run id", right_on="rna project.run id", how="left")  # Metadaten anfügen
barcodes = barcodes.fillna(0)
barcodes.to_csv("barcodes.tsv", sep="\t", index=False, header=False)
barcodes.head()

,rna project.run id,TubeID,meta TubeID,export_psn,meta pop visit_1_date,meta pop visit_2_date,meta pop visit_3_date,meta pop visit_4_date,meta pop age,meta pop age_dec,...,ang_pect,ang_pect1,lvedv,lvesv,schlagvolumen,pulm_syst_geschw,pulm_dias_geschw,gec_pd_copd,gec_pd_hypert,gec_vitals_so2
0,plt1.run1 pat_88,LV1007699778,LV1007699778,0,0,0,0,0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,plt1.run1 pat_89,LV1007699743,LV1007699743,0,0,0,0,0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,plt1.run1 pat_90,LV1007699757,LV1007699757,0,0,0,0,0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,plt1.run1 pat_91,LV1007699878,LV1007699878,0,0,0,0,0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,plt1.run1 pat_92,FR02512249,FR02512249,0,0,0,0,0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
barcodes = pd.read_csv("barcodes.tsv", decimal=".", sep="\t") # Barcodes-Datei speichern

### 4. --- Count-Matrix erstellen aus Gen-Metadaten ---

In [22]:
counts = gene_df.iloc[:, 18:].fillna(0) # Zählwerte extrahieren und NaN durch 0 ersetzen
counts

,plt1.run1 pat_88,plt1.run1 pat_89,plt1.run1 pat_90,plt1.run1 pat_91,plt1.run1 pat_92,plt1.run1 pat_93,plt1.run1 pat_94,plt1.run1 pat_95,plt1.run1 pat_96,plt1.run1 pat_97,...,plt49.run1 pat_3563,plt49.run1 pat_3564,plt49.run1 pat_3565,plt49.run1 pat_3566,plt49.run1 pat_3567,plt49.run1 pat_3568,plt49.run1 pat_3569,plt49.run1 pat_3570,plt49.run1 pat_3571,plt49.run1 pat_3572
0,2,0,0,3,3,0,1,1,16,11,...,5,2,2,0,2,0,1,2,1,0
1,0,0,0,0,0,0,0,0,0,3,...,0,0,1,0,0,0,0,0,0,0
2,225,34,13,102,156,175,389,450,224,157,...,198,96,90,287,309,94,62,215,261,131
3,73,17,2,48,102,27,65,62,90,73,...,40,21,70,39,71,15,26,66,41,17
4,0,0,0,0,4,0,2,1,0,0,...,0,0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57026,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57027,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57028,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57029,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57030,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
sparse_matrix = coo_matrix(counts.values) # Sparse-Matrix erstellen
sparse_matrix

<COOrdinate sparse matrix of dtype 'object'
	with 208790491 stored elements and shape (57031, 3661)>

In [24]:
mmwrite("matrix.mtx", sparse_matrix) # MTX-Datei speichern

### 5. --- Anndata-Objekt aus .mtx, barcodes.tsv und genes.tsv erstellen ---

In [25]:
mtx_tsv = 'matrix.mtx' # Datei, die die Counts enthält
barcodes_tsv = 'barcodes.tsv' # Datei, die Barcode-Informationen enthält
variables_tsv = 'variables.tsv' # Datei, die variable Informationen enthält

In [26]:
print(pat_df.shape, barcodes.shape, gene_df.shape, features.shape) # Shape überprüfen

(3776, 92) (3660, 92) (57031, 3679) (57031, 18)

In [27]:
print(features[features.duplicated(subset=features.columns[0], keep=False)])

Empty DataFrame
Columns: [Ensembl gene, Ensembl gene id, Ensembl biotype, UniProt proteins, UniProt genes, UniProt accessions, UniProt names, UniProt Ensembl transcripts, UniProt Ensembl proteins, UniProt Ensembl gene ids, Ensembl chr, Ensembl start, Ensembl stop, Ensembl strand, KEGG PATHWAY terms, KEGG PATHWAY ids, Gene Ontology terms, Gene Ontology ids]
Index: []

In [28]:
"MCM5" in gene_df["Ensembl gene"].values

True

In [29]:
if path_mtx:
    adata = assembler.from_mtx(path_mtx, mtx=mtx_tsv, barcodes=barcodes_tsv, variables=variables_tsv)

[INFO] Reading files: 1 of 1

### 6. --- AnnData vorbereiten ---

In [30]:
# Adata Obs einen Header hinzufügren
adata.obs_names.name = 'rna project.run id'
obs_columns_list = pat_df.columns.tolist()
obs_columns_list.remove('rna project.run id')
obs_columns_list.append('filename') # möglicherweise muss die komplette Spalte raus
obs_columns_list.append('rel_path') # möglicherweise muss die komplette Spalte raus
obs_header = obs_columns_list
adata.obs.columns = obs_header
adata

AnnData object with n_obs × n_vars = 3661 × 57031
    obs: 'TubeID', 'meta TubeID', 'export_psn', 'meta pop visit_1_date', 'meta pop visit_2_date', 'meta pop visit_3_date', 'meta pop visit_4_date', 'meta pop age', 'meta pop age_dec', 'meta pop sex', 'meta pop c19_severity', 'meta pop cohort', 'meta suep_hap export_psn', 'meta suep_hap baseline_date', 'meta suep_hap end_acute_date', 'meta suep_hap end_acute_visit_date', 'meta suep_hap m3_fu_date', 'meta suep_hap m6_fu_date', 'meta suep_hap m12_fu_date', 'meta suep_hap m24_fu_date', 'meta suep_hap age', 'meta suep_hap age_dec', 'meta suep_hap sex', 'meta suep_hap c19_severity', 'meta suep_hap cohort', 'meta export_psn', 'meta age', 'meta age_dec', 'meta sex', 'meta c19_severity', 'meta cohort', 'rna TubeID', 'rna id', 'rna fastq1', 'rna project', 'rna run', 'rna plate', 'rna organism', 'rna assembly', 'rna release', 'rna parameters', 'rna reads processed', 'rna reads with exactly 1 alignment', 'rna reads with multiple alignments', 'rna reads with no alignment', 'rna reads aligned', 'rna % reads aligned', 'rna duplicate reads', 'rna % duplicate reads', 'rna mitochondrial reads', 'rna % mitochondrial reads', 'rna rrna subunit reads', 'rna % rrna subunit reads', 'rna pcr bottleneck coefficient', 'rna mean fragment size (only for paired-end)', 'rna reads used for further steps (after optional filters for multimap, duplicate, mitochondria, rrna)', 'rna parameters.1', 'rna reads processed.1', 'rna reads assigned', 'rna % reads assigned total', 'rna % features with cpm >= 0.5', 'rna unassigned reads overlapping multiple genes', 'rna unassigned reads mapping to multiple locations', 'rna unassigned reads mapping to no feature', 'rna unassigned reads not mapping', 'rna unassigned reads due to bad mapping quality', 'rna unassigned reads due to low fragment length', 'rna unassigned chimeric reads', 'rna usable sample: mapped reads > 2000000', 'rna DDX3Y', 'rna XIST', 'rna gender', 'rna sample id original', 'rna plate id original', 'mnpvisid', 'mnpcvpid', 'mnpvislabel', 'gec_cv_hypert', 'gec_cv_chd', 'gec_cv_mi', 'anam_herz3', 'ang_pect', 'ang_pect1', 'lvedv', 'lvesv', 'schlagvolumen', 'pulm_syst_geschw', 'pulm_dias_geschw', 'gec_pd_copd', 'gec_pd_hypert', 'gec_vitals_so2', 'filename', 'rel_path'
    var: '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17'

In [31]:
var_header = features.columns.tolist()
var_header.remove("Ensembl gene")
adata.var_names.name = "Ensembl gene"
adata.var.columns = var_header

In [32]:
with pd.option_context('display.max_rows', 5,'display.max_columns', None):
    display(adata.obs)
    display(adata.var)

,TubeID,meta TubeID,export_psn,meta pop visit_1_date,meta pop visit_2_date,meta pop visit_3_date,meta pop visit_4_date,meta pop age,meta pop age_dec,meta pop sex,meta pop c19_severity,meta pop cohort,meta suep_hap export_psn,meta suep_hap baseline_date,meta suep_hap end_acute_date,meta suep_hap end_acute_visit_date,meta suep_hap m3_fu_date,meta suep_hap m6_fu_date,meta suep_hap m12_fu_date,meta suep_hap m24_fu_date,meta suep_hap age,meta suep_hap age_dec,meta suep_hap sex,meta suep_hap c19_severity,meta suep_hap cohort,meta export_psn,meta age,meta age_dec,meta sex,meta c19_severity,meta cohort,rna TubeID,rna id,rna fastq1,rna project,rna run,rna plate,rna organism,rna assembly,rna release,rna parameters,rna reads processed,rna reads with exactly 1 alignment,rna reads with multiple alignments,rna reads with no alignment,rna reads aligned,rna % reads aligned,rna duplicate reads,rna % duplicate reads,rna mitochondrial reads,rna % mitochondrial reads,rna rrna subunit reads,rna % rrna subunit reads,rna pcr bottleneck coefficient,rna mean fragment size (only for paired-end),"rna reads used for further steps (after optional filters for multimap, duplicate, mitochondria, rrna)",rna parameters.1,rna reads processed.1,rna reads assigned,rna % reads assigned total,rna % features with cpm >= 0.5,rna unassigned reads overlapping multiple genes,rna unassigned reads mapping to multiple locations,rna unassigned reads mapping to no feature,rna unassigned reads not mapping,rna unassigned reads due to bad mapping quality,rna unassigned reads due to low fragment length,rna unassigned chimeric reads,rna usable sample: mapped reads > 2000000,rna DDX3Y,rna XIST,rna gender,rna sample id original,rna plate id original,mnpvisid,mnpcvpid,mnpvislabel,gec_cv_hypert,gec_cv_chd,gec_cv_mi,anam_herz3,ang_pect,ang_pect1,lvedv,lvesv,schlagvolumen,pulm_syst_geschw,pulm_dias_geschw,gec_pd_copd,gec_pd_hypert,gec_vitals_so2,filename,rel_path
rna project.run id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
plt1.run1 pat_88,LV1007699778,LV1007699778,0,0,0,0,0,0.0,0,0,0,0,hap_0178,17/11/2021,24/11/2021,24/11/2021,0,0,0,0,65.0,60-69,M,severe,hap,hap_0178,65.0,60-69,M,severe,hap,LV1007699778,pat_88,AAAVY52HV_NAPKON_Plate1_2_22s004137-1-1_Valasa...,plt1,run1,plate1,human,hg38,104.0,"mode: single-end, keep duplicates: no, keep mu...","29,112,743","23,152,813","4,044,454","1,915,476","27,197,267",93.0,"20,093,139",73.0,"1,714,158",6.0,"1,868,907",6.0,0.28,0.0,"6,644,895",-t exon -g gene_id -s 2; multi-mapping: no; du...,"6,644,895","4,810,861",16.0,49.0,216.360,0.0,"1,617,674",0.0,0.0,0.0,0.0,True,844.0,8.0,M,Sample 49,Plate 1,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,matrix.mtx,.
plt1.run1 pat_89,LV1007699743,LV1007699743,0,0,0,0,0,0.0,0,0,0,0,suep_0425,08/11/2021,17/11/2021,17/11/2021,0,0,0,0,61.0,60-69,M,mild,suep,suep_0425,61.0,60-69,M,mild,suep,LV1007699743,pat_89,AAAVY52HV_NAPKON_Plate1_2_22s004137-1-1_Valasa...,plt1,run1,plate1,human,hg38,104.0,"mode: single-end, keep duplicates: no, keep mu...","24,355,220","13,253,462","7,713,379","3,388,379","20,966,841",86.0,"17,678,467",84.0,"1,475,002",7.0,"6,372,269",30.0,0.22,0.0,"2,989,995",-t exon -g gene_id -s 2; multi-mapping: no; du...,"2,989,995","2,155,768",8.0,45.0,97.961,0.0,"736,266",0.0,0.0,0.0,0.0,True,670.0,4.0,M,Sample 50,Plate 1,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,matrix.mtx,.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
plt49.run1 pat_3571,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0,0.0,0,0.0,0,0.0,0,0.0,0.00,0.0,0,0,0,0,0.0,0.0,0.000,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,matrix.mtx,.
plt49.run1 pat_3572,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0,0.0,0,0.0,0,0.0,0,0.0,0.00,0.0,0,0,0,0,0.0,0.0,0.000,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,matrix.mtx,.

,Ensembl gene id,Ensembl biotype,UniProt proteins,UniProt genes,UniProt accessions,UniProt names,UniProt Ensembl transcripts,UniProt Ensembl proteins,UniProt Ensembl gene ids,Ensembl chr,Ensembl start,Ensembl stop,Ensembl strand,KEGG PATHWAY terms,KEGG PATHWAY ids,Gene Ontology terms,Gene Ontology ids
Ensembl gene,,,,,,,,,,,,,,,,,
SDK1,ENSG00000146555,protein_coding,Protein sidekick-1,SDK1,Q7Z5N4; F8W6X9; A0A087WTQ6,SDK1_HUMAN; F8W6X9_HUMAN; A0A087WTQ6_HUMAN,ENST00000404826; ENST00000389531; ENST00000615806,ENSP00000385899; ENSP00000374182; ENSP00000478062,ENSG00000146555,chr7,3301252,4269000,+,0,0,"eye development, neural retina development, bi...","GO:0001654, GO:0003407, GO:0005488, GO:0005515..."
ENSG00000283537,ENSG00000283537,transcribed_unprocessed_pseudogene,0,0,0,0,0,0,ENSG00000283537,chr7,143620943,143645675,+,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000270696,ENSG00000270696,lncRNA,0,0,0,0,0,0,ENSG00000270696,chr2,75660462,75662208,+,0,0,0,0
SNRPGP11,ENSG00000229906,processed_pseudogene,0,0,0,0,0,0,ENSG00000229906,chr13,51496020,51496251,-,0,0,0,0

In [33]:
pat_df.columns.tolist()

['TubeID',
 'meta TubeID',
 'export_psn',
 'meta pop visit_1_date',
 'meta pop visit_2_date',
 'meta pop visit_3_date',
 'meta pop visit_4_date',
 'meta pop age',
 'meta pop age_dec',
 'meta pop sex',
 'meta pop c19_severity',
 'meta pop cohort',
 'meta suep_hap export_psn',
 'meta suep_hap baseline_date',
 'meta suep_hap end_acute_date',
 'meta suep_hap end_acute_visit_date',
 'meta suep_hap m3_fu_date',
 'meta suep_hap m6_fu_date',
 'meta suep_hap m12_fu_date',
 'meta suep_hap m24_fu_date',
 'meta suep_hap age',
 'meta suep_hap age_dec',
 'meta suep_hap sex',
 'meta suep_hap c19_severity',
 'meta suep_hap cohort',
 'meta export_psn',
 'meta age',
 'meta age_dec',
 'meta sex',
 'meta c19_severity',
 'meta cohort',
 'rna TubeID',
 'rna id',
 'rna fastq1',
 'rna project',
 'rna run',
 'rna plate',
 'rna organism',
 'rna assembly',
 'rna release',
 'rna parameters',
 'rna reads processed',
 'rna reads with exactly 1 alignment',
 'rna reads with multiple alignments',
 'rna reads with no alignment',
 'rna reads aligned',
 'rna % reads aligned',
 'rna duplicate reads',
 'rna % duplicate reads',
 'rna mitochondrial reads',
 'rna % mitochondrial reads',
 'rna rrna subunit reads',
 'rna % rrna subunit reads',
 'rna pcr bottleneck coefficient',
 'rna mean fragment size (only for paired-end)',
 'rna reads used for further steps (after optional filters for multimap, duplicate, mitochondria, rrna)',
 'rna parameters.1',
 'rna reads processed.1',
 'rna reads assigned',
 'rna % reads assigned total',
 'rna % features with cpm >= 0.5',
 'rna unassigned reads overlapping multiple genes',
 'rna unassigned reads mapping to multiple locations',
 'rna unassigned reads mapping to no feature',
 'rna unassigned reads not mapping',
 'rna unassigned reads due to bad mapping quality',
 'rna unassigned reads due to low fragment length',
 'rna unassigned chimeric reads',
 'rna usable sample: mapped reads > 2000000',
 'rna project.run id',
 'rna DDX3Y',
 'rna XIST',
 'rna gender',
 'rna sample id original',
 'rna plate id original',
 'mnpvisid',
 'mnpcvpid',
 'mnpvislabel',
 'gec_cv_hypert',
 'gec_cv_chd',
 'gec_cv_mi',
 'anam_herz3',
 'ang_pect',
 'ang_pect1',
 'lvedv',
 'lvesv',
 'schlagvolumen',
 'pulm_syst_geschw',
 'pulm_dias_geschw',
 'gec_pd_copd',
 'gec_pd_hypert',
 'gec_vitals_so2']

In [34]:
# .obs-Spaltennamen, die gelöscht werden sollen
drop_obs = []

# .obs-Spaltennamen, die geändert werden sollen. z.B. "old_name": "new_name"
# Beispiel: "old_name" = "rna usable sample: mapped reads > 2000000" -> Regex bevorzugt
rename_obs = {'rna reads used for further steps (after optional filters for multimap, duplicate, mitochondria, rrna)':'rna reads used after filters', 'rna usable sample: mapped reads > 2000000':'mapped reads > 2000000'} 

#Namen ändern mithilfe von Regex
replace_obs = {'unassigned':'unass.','due to':'',' ':'_','%':'pct',':':'_of','>=':'at_least','>':'over'}
replace_var = {' ':'_'}

# .var-Spaltennamen, die gelöscht werden sollen
drop_var = []

# .var-Spaltennamen, die geändert werden sollen. z.B. "old_name": "new_name"
rename_var = {}

In [35]:
# Änderungen an .obs-Spaltennamen in eine Kopie absspeichern
obs = adata.obs.copy()

obs.drop(columns=drop_obs, inplace=True)
obs.rename(columns=rename_obs, errors='raise', inplace=True)

# Änderungen an .var-Spaltennamen in eine Kopie absspeichern
var = adata.var.copy()

var.drop(columns=drop_var, inplace=True)
var.rename(columns=rename_var, errors='raise', inplace=True)

# Anderungen vornehmen
for x, y in replace_obs.items():
    obs.columns= obs.columns.str.replace(x, y, regex=True)
    
for x, y in replace_var.items():
    var.columns= var.columns.str.replace(x, y, regex=True) 
    
# Änderungen an AnnData anwenden
adata.obs = obs
adata.var = var

In [36]:
# Änderung dtype, wenn nicht automatisch übernommen
adata.obs["mapped_reads_over_2000000"] = adata.obs["mapped_reads_over_2000000"].astype("category")

### 7. --- AnnData-Objekt speichern ---

In [37]:
display(adata) # Übersicht

AnnData object with n_obs × n_vars = 3661 × 57031
    obs: 'TubeID', 'meta_TubeID', 'export_psn', 'meta_pop_visit_1_date', 'meta_pop_visit_2_date', 'meta_pop_visit_3_date', 'meta_pop_visit_4_date', 'meta_pop_age', 'meta_pop_age_dec', 'meta_pop_sex', 'meta_pop_c19_severity', 'meta_pop_cohort', 'meta_suep_hap_export_psn', 'meta_suep_hap_baseline_date', 'meta_suep_hap_end_acute_date', 'meta_suep_hap_end_acute_visit_date', 'meta_suep_hap_m3_fu_date', 'meta_suep_hap_m6_fu_date', 'meta_suep_hap_m12_fu_date', 'meta_suep_hap_m24_fu_date', 'meta_suep_hap_age', 'meta_suep_hap_age_dec', 'meta_suep_hap_sex', 'meta_suep_hap_c19_severity', 'meta_suep_hap_cohort', 'meta_export_psn', 'meta_age', 'meta_age_dec', 'meta_sex', 'meta_c19_severity', 'meta_cohort', 'rna_TubeID', 'rna_id', 'rna_fastq1', 'rna_project', 'rna_run', 'rna_plate', 'rna_organism', 'rna_assembly', 'rna_release', 'rna_parameters', 'rna_reads_processed', 'rna_reads_with_exactly_1_alignment', 'rna_reads_with_multiple_alignments', 'rna_reads_with_no_alignment', 'rna_reads_aligned', 'rna_pct_reads_aligned', 'rna_duplicate_reads', 'rna_pct_duplicate_reads', 'rna_mitochondrial_reads', 'rna_pct_mitochondrial_reads', 'rna_rrna_subunit_reads', 'rna_pct_rrna_subunit_reads', 'rna_pcr_bottleneck_coefficient', 'rna_mean_fragment_size_(only_for_paired-end)', 'rna_reads_used_after_filters', 'rna_parameters.1', 'rna_reads_processed.1', 'rna_reads_assigned', 'rna_pct_reads_assigned_total', 'rna_pct_features_with_cpm_at_least_0.5', 'rna_unass._reads_overlapping_multiple_genes', 'rna_unass._reads_mapping_to_multiple_locations', 'rna_unass._reads_mapping_to_no_feature', 'rna_unass._reads_not_mapping', 'rna_unass._reads__bad_mapping_quality', 'rna_unass._reads__low_fragment_length', 'rna_unass._chimeric_reads', 'mapped_reads_over_2000000', 'rna_DDX3Y', 'rna_XIST', 'rna_gender', 'rna_sample_id_original', 'rna_plate_id_original', 'mnpvisid', 'mnpcvpid', 'mnpvislabel', 'gec_cv_hypert', 'gec_cv_chd', 'gec_cv_mi', 'anam_herz3', 'ang_pect', 'ang_pect1', 'lvedv', 'lvesv', 'schlagvolumen', 'pulm_syst_geschw', 'pulm_dias_geschw', 'gec_pd_copd', 'gec_pd_hypert', 'gec_vitals_so2', 'filename', 'rel_path'
    var: 'Ensembl_gene_id', 'Ensembl_biotype', 'UniProt_proteins', 'UniProt_genes', 'UniProt_accessions', 'UniProt_names', 'UniProt_Ensembl_transcripts', 'UniProt_Ensembl_proteins', 'UniProt_Ensembl_gene_ids', 'Ensembl_chr', 'Ensembl_start', 'Ensembl_stop', 'Ensembl_strand', 'KEGG_PATHWAY_terms', 'KEGG_PATHWAY_ids', 'Gene_Ontology_terms', 'Gene_Ontology_ids'

In [38]:
adata_output = "anndata_1.h5ad"
utils.adata.save_h5ad(adata, adata_output) # speichern

[INFO] The adata object was saved to: anndata_1.h5ad

In [39]:
sctoolbox.settings.close_logfile()